#!/bin/bash
FONT='-*-gohufont-medium-*-*-*-14-*-*-*-*-*-*-*'
x=$(xdotool getmouselocation | egrep -oh "[0-9]+" | head -n 1)
# w=$(( $x < 1366 ? 1360 : 1440 ))
# h=$(( $x < 1366 ? 768 : 900 ))
w=1920
h=1080
nb='#2d2d2d'
sb='#2d2d2d'
nf='#dedede'
sf='#8b9dc3'

dmenu_command="dmenu -h $h -w $w -fn $FONT -nb $nb -nf $nf -sb $sb -sf $sf" 
