#!/bin/env zsh

bspc config border_width 2

#i=1
#echo $(bspc query -M) > /tmp/bspwm1.log
#for monitor in $(bspc query -M | tac); do
    # bspc monitor $monitor -n $i -d \
    #     $(echo -e '\uf0ac') \
    #     $(echo -e '\uf121') \
    #     $(echo -e '\uf120') \
    #     $(echo -e '\uf109') \
    #     $(echo -e '\uf03e') \
    #     $(echo -e '\uf0c3') \
    #     $(echo -e '\uf001') \
    #     $(echo -e '\uf135')
    # order:
    # internet
    # editor
    # terminal
    # desktop
    # image
    # player 
    # music
    # rocket
    # let i++
# done
# NMON=$i
# unset i

bspc monitor -n 1 -d \
    $(echo -e '\uf0ac')   `# internet` \
    $(echo -e '\uf121')   `# editor` \
    $(echo -e '\uf120')   `# terminal ` \
    $(echo -e '\uf15c')   `# document` \
    $(echo -e '\uf109')   `# desktop` \
    $(echo -e '\uf03e')   `# image` \
    $(echo -e '\uf16a')   `# player` \
    $(echo -e '\uf025')   `# music` \
    $(echo -e '\uf135')   `# rocket` \
    $(echo -e '\uf013')   `# gear`
# bspc monitor "eDP1" -n 2 -d \
#     $(echo -e '\uf0ac')  `#internet` \
#     $(echo -e '\uf121')  `# editor` \
#     $(echo -e '\uf120')  `# terminal` \
#     $(echo -e '\uf02d')  `# man` \
#     $(echo -e '\uf025')  `# music` \
#     $(echo -e '\uf21e')  `# heartbeat` \
#     $(echo -e '\uf094')  `# lemon` \
#     $(echo -e '\uf130')  `# phone`
# # bspc monitor "eDP1" -n 1 -d internet editor terminal document desktop image player music rocket gear
NMON=1

# bspc monitor ^1 -s ^2

bspc config top_padding 40
bspc config window_gap 6

# Visual options
#bspc config split_ratio 0.52
#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config border_width 3

# colors
bspc config focused_border_color "#6699cc"
bspc config active_border_color "#232826"
bspc config normal_border_color "#232826"
bspc config presel_border_color "#5080C9"
bspc config urgent_border_color "EF5847"

bspc config pointer-modifier mod4

# Rules
bspc rule -a sxiv state=floating center=on
bspc rule -a lxappearance desktop="^8" state=floating center=on
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a libreoffice-writer  follow=on desktop="^4"

bspc rule -a google-chrome follow=on desktop="^1"
bspc rule -a vivaldi-stable follow=on desktop="^1"
bspc rule -a firefox follow=on desktop="^1"

bspc rule -a gimp state=floating desktop="^6"
bspc rule -a vlc follow=on desktop="^8"
bspc rule -a mpv follow=on desktop="^8"
bspc rule -a Anki state=floating center=on
bspc rule -a "com-chschmid-jdotxt-Jdotxt" state=floating sticky=on

if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

nvidia-settings --assign CurrentMetaMode="HDMI-0: nvidia-auto-select +0+0 {ForceFullCompositionPipeline = On}, DVI-I-0: nvidia-auto-select +1360+0 {ForceFullCompositionPipeline = On}"
#compton -bcG & # backhround, draw shadows, not on panel
#conky -c dotfiles/conkyrc2  # clock

xrdb -merge /home/pinusc/.Xresources &
# setxkbmap it
xmodmap ~/.Xmodmap
sxhkd &
# clipmenud &

feh --recursive --randomize --bg-fill /home/pinusc/.wallpaper
# feh --bg-fill /home/pinusc/.wallpaper/theshowmustgoon_eidt.jpg
# randomwallpaper.sh

# so the pointer appears in the middle of the first monitor
# xdotool mousemove 680 384 &
xsetroot -cursor_name left_ptr &

# disable screensaver
# xset s off & xset -dpms & xset s noblank &
# # avoid screen tearing
compton -cbGf &
xautolock -time 15 -locker lock &
redshift -t 5500:3700 &

panel &
# (sleep 1; bspc config -m 1 top_padding 36) &
bspc config -m 1 top_padding 39 &
# polybar example &
mpd &
music_player &
bspc desktop -f \^1
