#!/bin/zsh

source $HOME/bin/lib/colors.sh

if [[ -n $(xrandr --listproviders | grep NVIDIA-0) ]]; then
    xrandr --setprovideroutputsource modesetting NVIDIA-0
fi
xrandr --auto

which nvidia-settings && nvidia-settings -l

NMON=$(xrandr --query | grep " connected" | wc -l)

bspc monitor "^1" -d \
    $(echo -e '\uf0c3')   `# flask` \
    $(echo -e '\uf109')   `# desktop` \
    $(echo -e '\uf025')   `# music` \
    $(echo -e '\uf0e0')   `# mail` \
    $(echo -e '\uf15c')   `# document` \
    $(echo -e '\uf0ac')   `# internet` \
    $(echo -e '\uf121')   `# editor` \
    $(echo -e '\uf120')   `# terminal ` \
    $(echo -e '\uf135')   `# rocket` \
    $(echo -e '\uf2db')   `# microchip` \
    $(echo -e '\uf21e')   `# hearthbeat`
if [[ "$NMON" -gt 1 ]]; then
    bspc monitor "^2" -d \
        $(echo -e '\uf121')  `# editor` \
        $(echo -e '\uf120')  `# terminal` \
        $(echo -e '\uf02d')  `# man` \
        $(echo -e '\uf025')  `# music` \
        $(echo -e '\uf15c')  `# document` \
        $(echo -e '\uf0ac')  `#internet` \
        $(echo -e '\uf21e')  `# heartbeat` \
        $(echo -e '\uf094')  `# lemon` \
        $(echo -e '\uf130')  `# phone` \ 
        $(echo -e '\uf2db')  `# microchip` \
        $(echo -e '\uf21e')  `# hearthbeat`
fi

# bspc monitor ^1 -s ^2
bspc config window_gap 6

# Visual options
#bspc config split_ratio 0.52
#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config border_width 2
# colors
bspc config focused_border_color $c_green
bspc config active_border_color $c_green
bspc config sticky_border_color $c_red
bspc config normal_border_color $base00
bspc config presel_feedback_color $c_yellow
bspc config urgent_border_color $c_red

bspc config pointer-modifier mod4

# Rules
bspc rule -a Nsxiv state=floating center=on layer=above
bspc rule -a Emacs state=tiled
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a libreoffice-writer state=tiled follow=on desktop="^5"

# bspc rule -a Firefox follow=on desktop="^6"
# bspc rule -a qutebrowser follow=on desktop="^6"

bspc rule -a gimp state=floating desktop="^1"
bspc rule -a vlc follow=on desktop="^2"
bspc rule -a mpv follow=on desktop="^2"
bspc rule -a XCalc state=floating center=on
bspc rule -a Anki state=floating center=on
bspc rule -a "*:urxvt-quaked" state=floating
bspc rule -a "*:quake-tabbed" state=floating
bspc rule -a "Zathura" state=tiled
bspc rule -a "dragon-drag-and-drop" follow=on
. "$XDG_CONFIG_HOME/bspwm/bspwm_rules"

if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi
bspc desktop -f \^6 &

if xdpyinfo | grep -q VNC-EXTENSION; then
    xrandr --output VNC-0 --primary
fi

#=============================== VIDEO SETTINGS ================================

# nvidia-settings --assign CurrentMetaMode="HDMI-0: nvidia-auto-select +1440+0 {ForceFullCompositionPipeline = On}, DVI-I-0: nvidia-auto-select +0+0 {ForceFullCompositionPipeline = On}" &
picom --vsync -cb
dock_handler.sh  # can now automatically infer if docked
setxkbmap -layout 'us(altgr-intl)'

#==================================== XORG =====================================
# Don't background this, so everything will use correct settings
xrdb -merge /home/pinusc/.Xresources
xset fp+ /usr/share/fonts/X11/gohu &
# setxkbmap it
xmodmap ~/.Xmodmap
xcape -e 'Control_R=Escape;Control_L=Escape'
xsetroot -cursor_name crosshair &
dunst &

#=================================== SCREEN ====================================
feh --recursive --randomize --bg-fill /home/pinusc/.wallpaper &

# disable screensaver
xautolock -time 15 -locker lock &
redshift -t 6500:2000 -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &>~/tmp/redshift.log &

#==================================== APPS =====================================
clipmenud &
sxhkd &
panel &
bspc config -m primary top_padding 55 &
music_player &
/usr/lib/kdeconnectd &
blueman-applet &
jellyfin-mpv-shim &>~/tmp/jellyfin-mpv-shim.log &
