#!/bin/zsh

source $HOME/bin/lib/colors.sh

if [[ -n $(xrandr --listproviders | grep NVIDIA-0) ]]; then
    xrandr --setprovideroutputsource modesetting NVIDIA-0
fi
xrandr --auto

which nvidia-settings && nvidia-settings -l

NMON=$(xrandr --query | grep " connected" | wc -l)

bspc monitor "^1" -d \
    $(echo -e '\uf0c3')   `# flask` \
    $(echo -e '\uf109')   `# desktop` \
    $(echo -e '\uf025')   `# music` \
    $(echo -e '\uf0e0')   `# mail` \
    $(echo -e '\uf15c')   `# document` \
    $(echo -e '\uf0ac')   `# internet` \
    $(echo -e '\uf121')   `# editor` \
    $(echo -e '\uf120')   `# terminal ` \
    $(echo -e '\uf135')   `# rocket` \
    $(echo -e '\uf2db')   `# microchip` \
    $(echo -e '\uf21e')   `# hearthbeat`
if [[ NMON -gt 1 ]]; then
    bspc monitor "^2" -d \
        $(echo -e '\uf0ac')  `#internet` \
        $(echo -e '\uf121')  `# editor` \
        $(echo -e '\uf120')  `# terminal` \
        $(echo -e '\uf02d')  `# man` \
        $(echo -e '\uf025')  `# music` \
        $(echo -e '\uf21e')  `# heartbeat` \
        $(echo -e '\uf094')  `# lemon` \
        $(echo -e '\uf130')  `# phone`
fi

# bspc monitor ^1 -s ^2

# bspc config top_padding 40
bspc config window_gap 6

# Visual options
#bspc config split_ratio 0.52
#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config border_width 2
# colors
bspc config focused_border_color $c_green
bspc config active_border_color $c_green
bspc config normal_border_color $base00
bspc config presel_feedback_color $c_yellow
bspc config urgent_border_color $c_red

bspc config pointer-modifier mod4

# Rules
bspc rule -a sxiv state=floating center=on
bspc rule -a Emacs state=tiled
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a libreoffice-writer state=tiled follow=on desktop="^5"

bspc rule -a google-chrome follow=on desktop="^6"
bspc rule -a vivaldi-stable follow=on desktop="^6"
bspc rule -a Firefox follow=on desktop="^6"

bspc rule -a gimp state=floating desktop="^1"
bspc rule -a vlc follow=on desktop="^2"
bspc rule -a mpv state=floating center=on
bspc rule -a Anki state=floating center=on
bspc rule -a "com-chschmid-jdotxt-Jdotxt" state=floating sticky=on

if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi
sxhkd &

nvidia-settings --assign CurrentMetaMode="HDMI-0: nvidia-auto-select +1440+0 {ForceFullCompositionPipeline = On}, DVI-I-0: nvidia-auto-select +0+0 {ForceFullCompositionPipeline = On}" &
compton -bcG & # backhround, draw shadows, not on panel
#conky -c dotfiles/conkyrc2  # clock

xrdb -merge /home/pinusc/.Xresources &
# setxkbmap it
xmodmap ~/.Xmodmap
# clipmenud &

feh --recursive --randomize --bg-fill /home/pinusc/.wallpaper &
# feh --bg-fill /home/pinusc/.wallpaper/theshowmustgoon_eidt.jpg
# randomwallpaper.sh

# so the pointer appears in the middle of the first monitor
# xdotool mousemove 680 384 &
xsetroot -cursor_name left_ptr &

# disable screensaver
# xset s off & xset -dpms & xset s noblank &
# # avoid screen tearing
xautolock -time 15 -locker lock &
redshift -t 5500:3700 &
# git annex assistant --autostart

panel &
# (sleep 1; bspc config -m 1 top_padding 36) &
xset fp+ /usr/share/fonts/X11/gohu &
bspc config -m 1 top_padding 39 &
mpd &
music_player &
bspc desktop -f \^6 &
